name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches: '*'

jobs:
  ios_test:
    runs-on: macos-12

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup java
      uses: actions/setup-java@v2
      with: 
        distribution: temurin
        java-version: "11"

    - name: Setup Kotlin
      uses: fwilhe2/setup-kotlin@main
      with:
        version: 1.5.31

    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest

    - name: Run Swift tests
      run: xcodebuild test -workspace iosApp/iosApp.xcworkspace -scheme iosApp -destination 'platform=iOS Simulator,name=iPhone 11' OTHER_LDFLAGS=-lsqlite3

  android_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup java
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: "11"

    - name: Setup Kotlin
      uses: fwilhe2/setup-kotlin@main
      with:
        version: 1.6.10

    - name: Run Kotlin tests
      run: ./gradlew :shared:testDebugUnitTest cleanIosX64Test iosX64Test
